name: Deploy static content to GitHub Pages

on:
  # Run on pushes to the default branch (usually "main")
  push:
    branches:
      - main

# Permissions required for the GitHub token
permissions:
  contents: read
  pages: write

# Define concurrency settings
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Deployment job
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Use version 2 of the action

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Choose the Node.js version you need

      - name: Build Your Static Content
        run: |
          # Add commands to build your static content (e.g., npm run build)
          # Replace these with the actual build commands for your project
          npm install  # Install dependencies if needed
          npm run build  # Replace with your build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/templates  # Specify the directory with your built static content, including the 'templates' folder
